### ISSUE TITLE
Compile error 

### ISSUE THREAD

**Issue by huikang** [watson-developer-cloud/conversation-enhanced#102]
I use the gradle docker image to compile the application. The following are the error I got. Can anyone offer some help? Thanks.

[1] https://hub.docker.com/_/gradle/

```
angular2@2.0.0-beta.21 node_modules/angular2
:gulp_build
[18:45:01] Using gulpfile /conversation-with-discovery/gulpfile.js
[18:45:01] Starting 'build-ts'...
[18:45:01] Starting 'build-css'...
[18:45:01] Starting 'build-img'...
[18:45:01] Starting 'build-fonts'...
[18:45:01] Starting 'build-locale'...
[18:45:03] Finished 'build-locale' after 1.48 s
[18:45:03] css all files 33.7 kB
[18:45:03] Finished 'build-css' after 1.73 s

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: spawn /conversation-with-discovery/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor/gifsicle ENOENT
    at exports._errnoException (util.js:873:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
:gulp_build FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gulp_build'.
> Process 'command '/conversation-with-discovery/.gradle/nodejs/node-v4.4.7-linux-x64/bin/node'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

```

**Comment by huikang** [comment]
The build also failed using the official websphere liberty image [2]

[2]  https://hub.docker.com/_/websphere-liberty/

```
[19:18:10] Starting 'build-img'...
[19:18:10] Starting 'build-fonts'...
[19:18:10] Starting 'build-locale'...
[19:18:12] Finished 'build-locale' after 1.48 s
[19:18:12] css all files 33.7 kB
[19:18:12] Finished 'build-css' after 1.74 s

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: spawn /conversation-with-discovery/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor/gifsicle ENOENT
    at exports._errnoException (util.js:873:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
:gulp_build FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gulp_build'.
> Process 'command '/conversation-with-discovery/.gradle/nodejs/node-v4.4.7-linux-x64/bin/node'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2 mins 19.993 secs


```

**Comment by stevenpkg** [comment]
Not quite sure what your problem is here, can you clone or download and build localy

**Comment by huikang** [comment]
After applying [this change ](https://github.com/watson-developer-cloud/conversation-with-discovery/pull/103), the program can be compiled with locally.

**Comment by stevenpkg** [comment]
Okay great
